### ISSUE TITLE
Error after updating to 3.4.0

### ISSUE THREAD

**Issue by beirdostudio** [strongloop/loopback-connector-mongodb#411]
Hello,
I'm getting this error after updating to the mongodb connector v3.4.0
`Error: Cannot find module '../wireprotocol/2_4_support'`
the errors goes away when I go back to version 3.3.1

**Comment by beirdostudio** [comment]
after removing the node_modules directory and running npm install, it worked.
